# service.yaml

apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
    - port: 30020
  selector:
    app: wordpress
    tier: frontend
  type: NodePort
